# Generated by Django 5.2.4 on 2025-07-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramapp',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='instagram_apps',
            field=models.ManyToManyField(blank=True, help_text='Assign one or more Instagram Apps to this employee', related_name='employees', to='backend.instagramapp'),
        ),
    ]
